### ISSUE TITLE
Mini joy thrusters and checklist

### ISSUE THREAD

**Issue by Woof1** [domdavis/ch-products-elite-map#11]
the checklist won't fully recognize the throttle mini joy to accept. I've turned checklist off in settings but it keep coming up?

**Comment by domdavis** [comment]
This is usually a calibration issue. In the Control Manager unmap the sticks by clicking on the Direct button (Stick with three straight lines). Then click Test/Calibrate (Target icon) select then throttle and recalibrate it. Reload the map, reload elite, hopefully it'll be sorted.

**Comment by Woof1** [comment]
Thanks, unmapped, calibrated, downloaded map, loaded elite - didn't
recognize any controllers.  : (

On Mon, Aug 3, 2015 at 11:31 PM, Dom Davis <notifications@github.com> wrote:

> This is usually a calibration issue. In the Control Manager unmap the
> sticks by clicking on the Direct button (Stick with three straight lines).
> Then click Test/Calibrate (Target icon) select then throttle and
> recalibrate it. Reload the map, reload elite, hopefully it'll be sorted.
>
> > On 4 Aug 2015, at 02:18, Woof1 <notifications@github.com> wrote:
> >
> > the checklist won't fully recognize the throttle mini joy to accept.
> I've turned checklist off in settings but it keep coming up?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/domdavis/ch-products-elite-map/issues/11#issuecomment-127495535>
> .
>



-- 

 J.E.B. Pickett

**Comment by domdavis** [comment]
If you go into the calibration now is there one device?

If there is, go into the confit settings in elite and check its set to Custom still. 

If that is try repeating the installation instructions. If you've made no changes to the maps it should get everything back to where it should be. 

I'll try something tonight and see if there has been a bug introduced into the config when it's unmapped and remapped.

**Comment by Woof1** [comment]
Hi Dom - the calibration and reload finally worked but now I seem to
encounter a new problem.  When I restart the computer, I have no controls
in ED.  Had to go back, recopy and insert the config and start file into
the Local/Frontier folder, re-calibrated, re-mapped, saved, restarted and
it worked for 2 days.  Restarted to the computer today and again, no
joystick controls at all in ED (checked to make sure Custom was selected
each time).  Probably a bug in either ED or my computer?

Thanks for your help.

On Wed, Aug 5, 2015 at 11:46 AM, Dom Davis <notifications@github.com> wrote:

> If you go into the calibration now is there one device?
>
> If there is, go into the confit settings in elite and check its set to
> Custom still.
>
> If that is try repeating the installation instructions. If you've made no
> changes to the maps it should get everything back to where it should be.
>
> I'll try something tonight and see if there has been a bug introduced into
> the config when it's unmapped and remapped.
>
> > On 5 Aug 2015, at 19:00, Woof1 <notifications@github.com> wrote:
> >
> > Thanks, unmapped, calibrated, downloaded map, loaded elite - didn't
> > recognize any controllers. : (
> >
> > On Mon, Aug 3, 2015 at 11:31 PM, Dom Davis <notifications@github.com>
> wrote:
> >
> > > This is usually a calibration issue. In the Control Manager unmap the
> > > sticks by clicking on the Direct button (Stick with three straight
> lines).
> > > Then click Test/Calibrate (Target icon) select then throttle and
> > > recalibrate it. Reload the map, reload elite, hopefully it'll be
> sorted.
> > >
> > > > On 4 Aug 2015, at 02:18, Woof1 <notifications@github.com> wrote:
> > > >
> > > > the checklist won't fully recognize the throttle mini joy to accept.
> > > I've turned checklist off in settings but it keep coming up?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/domdavis/ch-products-elite-map/issues/11#issuecomment-127495535
> >
> > > .
> > >
> >
> >
> >
> > --
> >
> > J.E.B. Pickett
>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/domdavis/ch-products-elite-map/issues/11#issuecomment-128104870>
> .
>



-- 

 J.E.B. Pickett

**Comment by domdavis** [comment]
Each time you restart your computer you will need to load the CH Control manager and download the map before you start Elite. Let me know if that fixes the issue.

**Comment by Woof1** [comment]
Hi Dom - sorry for the delay, had a hard disk failure and just got my
mirror back up, set up and returned to normal.  It appears that the
bindings are holding at this point.  Thank you very much for your
assistance on this!

On Mon, Aug 10, 2015 at 10:58 AM, Dom Davis <notifications@github.com>
wrote:

> Each time you restart your computer you will need to load the CH Control
> manager and download the map before you start Elite. Let me know if that
> fixes the issue.
>
> > On 10 Aug 2015, at 18:41, Woof1 <notifications@github.com> wrote:
> >
> > Hi Dom - the calibration and reload finally worked but now I seem to
> > encounter a new problem. When I restart the computer, I have no controls
> > in ED. Had to go back, recopy and insert the config and start file into
> > the Local/Frontier folder, re-calibrated, re-mapped, saved, restarted and
> > it worked for 2 days. Restarted to the computer today and again, no
> > joystick controls at all in ED (checked to make sure Custom was selected
> > each time). Probably a bug in either ED or my computer?
> >
> > Thanks for your help.
> >
> > On Wed, Aug 5, 2015 at 11:46 AM, Dom Davis <notifications@github.com>
> wrote:
> >
> > > If you go into the calibration now is there one device?
> > >
> > > If there is, go into the confit settings in elite and check its set to
> > > Custom still.
> > >
> > > If that is try repeating the installation instructions. If you've made
> no
> > > changes to the maps it should get everything back to where it should
> be.
> > >
> > > I'll try something tonight and see if there has been a bug introduced
> into
> > > the config when it's unmapped and remapped.
> > >
> > > > On 5 Aug 2015, at 19:00, Woof1 <notifications@github.com> wrote:
> > > >
> > > > Thanks, unmapped, calibrated, downloaded map, loaded elite - didn't
> > > > recognize any controllers. : (
> > > >
> > > > On Mon, Aug 3, 2015 at 11:31 PM, Dom Davis <notifications@github.com
> >
> > > wrote:
> > > >
> > > > > This is usually a calibration issue. In the Control Manager unmap
> the
> > > > > sticks by clicking on the Direct button (Stick with three straight
> > > lines).
> > > > > Then click Test/Calibrate (Target icon) select then throttle and
> > > > > recalibrate it. Reload the map, reload elite, hopefully it'll be
> > > sorted.
> > > > >
> > > > > > On 4 Aug 2015, at 02:18, Woof1 <notifications@github.com> wrote:
> > > > > >
> > > > > > the checklist won't fully recognize the throttle mini joy to
> accept.
> > > > > I've turned checklist off in settings but it keep coming up?
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/domdavis/ch-products-elite-map/issues/11#issuecomment-127495535
> > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > >
> > > > J.E.B. Pickett
> > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/domdavis/ch-products-elite-map/issues/11#issuecomment-128104870
> >
>
> > > .
> > >
> >
> >
> >
> > --
> >
> > J.E.B. Pickett
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/domdavis/ch-products-elite-map/issues/11#issuecomment-129549858>
> .
>



-- 

 J.E.B. Pickett

**Comment by domdavis** [comment]
No worries. I'll leave the issue open for a couple of weeks just to make sure it's all sorted. If I hear nothing more I'll assume all is good and close it.

**Comment by domdavis** [comment]
Assuming this is now sorted. Shout if you have any more problems.
