### ISSUE TITLE
Root PresetName

### ISSUE THREAD

**Issue by n0izy** [domdavis/ch-products-elite-map#14]
Hi Dom,

I would strongly recommend changing the Root PresetName="Custom" to something else. 

I am new to Elite and was following your guide, and your custom profile kept getting overwritten by the game to defaults without axis when I was switching to Custom. I eventually found a thread about bindings getting overwritten and someone recommending to create a different profile name. I named your profile "DomDavis" and it now shows up in the in-game drop down profile and doesn't get overwritten like Custom was. Simple change that fixed a frustrating issue for someone who isn't sure yet how everything works.

Thanks for sharing your work.

**Comment by domdavis** [comment]
Wasn't aware you could do that :) It's set to Custom because that's what E:D does when you start playing with it. I'll do that in the next release. Cheers for letting me know.

**Comment by christopher-hopper** [comment]
@domdavis, @n0izy, 
I've made changes and tested them on Elite Dangerous Horizons. Seems to work well. 

See my pull request #15 and test.

**Comment by domdavis** [comment]
Merged the changes in. Shout if you have any problems. Thanks @christopher-hopper.
