### ISSUE TITLE
PDF Guide source

### ISSUE THREAD

**Issue by mnantel** [domdavis/ch-products-elite-map#25]
Greetings,

Thanks for this great sharing of an otherwise unpleasant process. Would you be able to also share the source file used for your mappings guide PDF file? I imagine CH Products has some form of source template for this that you modified?

Thanks!
Mat

**Comment by domdavis** [comment]
I've never managed to find a good template or the originator of the template I used to use. The one I use now I paid to have produced and there are licensing considerations depending on your desired use.

**Comment by mnantel** [comment]
Understood, thank you. Sounds like some PDF-to-vector work will be my solution - this is totally for personal use...

**Comment by domdavis** [comment]
I've added you to a project containing the assets which you can grab and use for personal use. I think GitHub limits me to 3 collaborators on free private projects so I'll operate access on a FIFO queue :)
