### ISSUE TITLE
Trouble with pre-flight checklist (thrust)

### ISSUE THREAD

**Issue by Dreams-Visions** [domdavis/ch-products-elite-map#5]
First, thank you for this.  Your map and setup have been just wonderful and everything is working well for me.

....except the tutorial pre-flight checklist.  For some reason, the thrust nob/nipple has problems being properly acknowledged.  I eventually had to switch controls to default kb&m so that I could get past it.  All the other checklist items and buttons work except those 4 thrust commands.  The trust works fine when flying...and I know the pre-flight checklist can be disabled outside of the tutorials...I guess I just wanted to make you aware of the issue.  If there's a way to make this behave properly, I'd love to know.

Otherwise, thank you for the great guide and map!

**Comment by domdavis** [comment]
I can't replicate this (I'm assuming it's latest version of the full map, not the redux map). When you try and perform the pre-flight checks does it start registering the axis and then suddenly stop and not complete? If so I've had issues with this before and it's to do with calibration/spurious input. It seems that if another axis registers input while doing pre-flight checks it cancels out the input of the axis being checked and makes it hard, if not impossible to complete the check.

Quite often it's the throttle that's doing this. There's a reasonable dead zone set on the stick and a larger one set on the thumb-stick as I find that doesn't always centre well. The throttle, on the other hand, doesn't have a dead zone at all.

Things you can try:

* Recalibrate the stick and throttle. If you need details on how to do this shout and I'll provide a walkthrough
* Disable analog throttle input temporarily. When you get to doing the lateral and vertical thrust checks press `alt` + `Throttle Hat 1 Right` to disable throttle input. Perform the thrust checks. Press `alt` + `Throttle Hat 1 Right` to re-enable throttle input again.

Let me know how you get on.

**Comment by Dreams-Visions** [comment]
Update!  It was actually that I needed to recalibrate my pro throttle :-/

It was creating  multiple issues.  Pulling the throttle back would never put the ship at 0 (lowest it would go was like 15 knots), and the thumb joystick was jumpy. Calibrating both relieved all issues.  Sorry for the false-alarm.  And again, thank you for the fantatic setup.

**Comment by domdavis** [comment]
No problems. Glad you got it sorted. I may add an FAQ section to the `README.md` listing things like this as it's got me before too. My controllers are over a decade old and seem to drift quite a bit if I don't recalibrate them every couple of weeks.

**Comment by domdavis** [comment]
No problems. Glad you got it sorted. I may add an FAQ section to the `README.md` listing things like this as it's got me before too. My controllers are over a decade old and seem to drift quite a bit if I don't recalibrate them every couple of weeks.
