### ISSUE TITLE
Custom binds for Galaxy and System Map are upside-down

### ISSUE THREAD

**Issue by christopher-hopper** [domdavis/ch-products-elite-map#8]
### Description

When using the Elite: Dangerous Galaxy Map or System Map to select navigation routes, the Throttle's joystick is mapped so that the "Y" axis controls the movement side-to-side, while the "X" axis controls movement up and down. This makes HOTAS navigation near impossible. I had been resorting to just using the mouse instead. 

### Steps to Reproduce

1. Follow the instructions for installation of the _CH Products Elite Map_ found in `README.md`.
1. Load the `redux.map` Joystick Mappings using _CH Control Manager_.
1. Start _Elite: Dangerous_ and enable the Custom control settings contained in the `Custom.binds`.
1. Play a Solo game and once in the Cockpit go to the _Galaxy Map_.
1. Using the Throttle min-joystick, move the map cursor to select a new navigation route. At this point you should notice that the cursor movement is not as you would expect.

### Suggested Solution

I've taken a look at the Options for Controls set by `config/Custom.binds` and found that the problem can be fixed by changing these options:

- *Galaxy Cam Translate Y-Axis* to `Joy RY-Axis` with _Invert Axis_ as `On`
    ![elitedangerouscontrolsgalaxycamy](https://cloud.githubusercontent.com/assets/452515/8395523/43ade788-1db8-11e5-845c-8c6fb8ac6976.jpg)

- *Galaxy Cam Translate X-Axis* to `Joy RZ-Axis` with _Invert Axis_ as `Off`
    ![elitedangerouscontrolsgalaxycamx](https://cloud.githubusercontent.com/assets/452515/8395522/1b372972-1db8-11e5-86d6-4ec4fb6f0525.jpg)

I've saved the resulting `Custom.binds` and will push it as a Pull Request for your consideration.

**Comment by domdavis** [comment]
It will be interesting to see if this is also an issue in the full map. I'll investigate tonight. When setting up the galaxy map controls I never found a layout I was really happy with so exclusively use the mouse. If the proposed layout is more logical for others then we'll go with that.

**Comment by domdavis** [comment]
Given the fix, both the `full` and `redux` map will be changed so no further updates are needed. Thanks for sorting this. Marking this as closed now.
